#!/usr/bin/env python3
"""Writes src/contrast.bats: WCAG 2 relative luminance and contrast as
dataprops. LIN is the sRGB transfer function tabulated for the 256
channel values (linear light times 100000, rounded down and up), the
one place numbers enter; everything else is the WCAG formula, checked
by the constraint solver."""
import math, os
root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

def lin(c):
    v = c / 255
    return v / 12.92 if v <= 0.04045 else ((v + 0.055) / 1.055) ** 2.4

rows = []
for c in range(256):
    x = lin(c) * 100000
    lo, hi = math.floor(x), math.ceil(x)
    rows.append(f"  | LIN_{c:02x}({c}, {lo}, {hi})")

src = f'''(* contrast -- WCAG 2 relative luminance and contrast ratio, proven
   (generated by scripts/gen-contrast.py: edit the script, not this file)

   A colour is a static int 0xRRGGBB. LUM(c, lo, hi) bounds its relative
   luminance: lo <= L * 10^9 <= hi. CONTRAST(a, b, k) says the contrast
   ratio of a and b is at least k / 10, as WCAG defines it:
   (L_lighter + 0.05) / (L_darker + 0.05). WCAG asks 4.5 (k = 45) for
   text, 3 (k = 30) for large text and for the parts of a control, 7
   (k = 70) for AAA text. *)

#include "share/atspre_staload.hats"

#use builder as B

(* The sRGB transfer function (IEC 61966-2-1, as WCAG 2 states it): a
   channel c / 255 in linear light, times 100000, between lo and hi *)
#pub dataprop LIN(int, int, int) =
{chr(10).join(rows)}

(* Relative luminance, times 10^9: 0.2126 R + 0.7152 G + 0.0722 B *)
#pub dataprop LUM(int, int, int) =
  | {{r,g,b:nat | r < 256; g < 256; b < 256}}{{rl,rh,gl,gh,bl,bh:int}}
    LUMc(r * 65536 + g * 256 + b,
         2126 * rl + 7152 * gl + 722 * bl, 2126 * rh + 7152 * gh + 722 * bh) of
      (LIN(r, rl, rh), LIN(g, gl, gh), LIN(b, bl, bh))

(* (L_lighter + 0.05) >= k/10 * (L_darker + 0.05), both times 10^9,
   with the lighter bound taken low and the darker high *)
#pub dataprop CONTRAST(int, int, int) =
  | {{a,b,k:int}}{{alo,ahi,blo,bhi:int | 10 * (alo + 50000000) >= k * (bhi + 50000000)}}
    CONTRAST_lighter_first(a, b, k) of (LUM(a, alo, ahi), LUM(b, blo, bhi))
  | {{a,b,k:int}}{{alo,ahi,blo,bhi:int | 10 * (blo + 50000000) >= k * (ahi + 50000000)}}
    CONTRAST_lighter_second(a, b, k) of (LUM(a, alo, ahi), LUM(b, blo, bhi))

fn _hexdigit {{d:nat | d < 16}} (d: int d): [v:nat | v < 256] int v =
  if d < 10 then 48 + d else 87 + d

(* The colour c as CSS: #rrggbb *)
#pub fn put_rgb {{c:nat | c < 16777216}}{{n:nat | n + 7 <= $B.BUILDER_CAP}}
  (b: !$B.builder(n) >> $B.builder(n + 7), c: int c): void

implement put_rgb {{c}}{{n}} (b, c) = let
  val () = $B.put_char(b, 35)
  val () = $B.put_char(b, _hexdigit(ndiv(c, 1048576)))
  val () = $B.put_char(b, _hexdigit(nmod(ndiv(c, 65536), 16)))
  val () = $B.put_char(b, _hexdigit(nmod(ndiv(c, 4096), 16)))
  val () = $B.put_char(b, _hexdigit(nmod(ndiv(c, 256), 16)))
  val () = $B.put_char(b, _hexdigit(nmod(ndiv(c, 16), 16)))
in $B.put_char(b, _hexdigit(nmod(c, 16))) end
'''
open(os.path.join(root, 'src', 'contrast.bats'), 'w').write(src)
